#! /usr/bin/env python
# -*- coding: utf-8 -*-

#   math2html: convert LaTeX equations to HTML output.
#
#   Copyright (C) 2009,2010 Alex Fernández
#   Released  without warranties or conditions of any kind
#   under the terms of the Apache License, Version 2.0
#   http://www.apache.org/licenses/LICENSE-2.0

#   Based on eLyXer: convert LyX source files to HTML output.
#   http://elyxer.nongnu.org/

