#! /usr/bin/env python
# -*- coding: utf-8 -*-

#   math2html: convert LaTeX equations to HTML output.
#
#   Copyright (C) 2009-2011 Alex Fernández
#   Released  without warranties or conditions of any kind
#   under the terms of the 2-Clause BSD license
#   http://www.opensource.org/licenses/BSD-2-Clause

#   Based on eLyXer: convert LyX source files to HTML output.
#   http://elyxer.nongnu.org/

