#!/bin/bash

#   eLyXer -- convert LyX source files to HTML output.
#
#   Copyright (C) 2009 Alex Fernández
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alex 2009-05-10: open all windows in the development environment

xfce4-terminal --geometry=197x50 --display :0.0 --working-directory ~/bulk/elyxer --tab --working-directory ~/bulk/elyxer/src --tab --working-directory ~/bulk/elyxer/src --tab --working-directory ~/bulk/elyxer/test &
thunar ~/bulk/elyxer/docs/

